site_name: Darren
nav :
 - Home : index.md
 - About : about.md
 - Philippines : Philippines.md
 - for my note : note.md
 - linux_container_virtualization_notes.md : 容器知識.md
theme:
  name: readthedocs
  logo: image/favicon.ico

