site_name: Darren
nav :
# - Home : index.md
 - About : about.md
 - 使用 MkDocs 建立文件網站教學筆記 : note.md
 - Linux 容器筆記 : 容器知識.md
 - Docker常用命令 :  docker_commands.md
 - Ansible簡介及用法 :  ansible簡介及用法.md
 - 運維知識 : 運維知識.md
 - operator介紹 : operator介紹.md
 - ocp命令 : ocp命令.md
 - ocp-prot介紹 : ocp-prot介紹.md
 - loki_pdb_維運整理: loki_pdb_維運整理.md
 - k8s命令: k8s命令.md
 - NotebookLM: NotebookLM.md
 - K8S-Storage: K8S-Storage.
 - k8s-pv-pvc-note k8s-pv-pvc-note.md
theme:
  name: readthedocs
  logo: image/favicon.ico

