apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-nginx
  labels:
    app: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: nginx
        image: registry.redhat.io/rhscl/nginx-116-rhel7
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/cache/nginx
          name: cache-volume
      volumes:
      - name: cache-volume
        emptyDir: {}
