apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-nginx
  labels:
    app: demo
spec:
  replicas: 2   # 建議保留，表示要跑幾個 Pod
  selector:
    matchLabels:    # 一定要有 selector，Deployment 才能管理 ReplicaSet/Pod
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 8080   # 不能用 80，因為 SCC 不允許低於 1024 的 port
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1000720001   # 落在 OpenShift SCC 允許的範圍
        volumeMounts:
        - name: cache-volume
          mountPath: /var/cache/nginx
        - name: run-volume
          mountPath: /var/run
      volumes:
      - name: cache-volume
        emptyDir: {}
      - name: run-volume
        emptyDir: {}
