spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 8080   # 注意這裡要改，不能用 80
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1000720001  # 落在允許範圍
