apiVersion: v1
kind: Service
metadata:
  name: demo-nginx-service
  labels:
    app: demo
spec:
  selector:
    app: demo
  ports:
  - protocol: TCP
    port: 80        # Service 對外還是用 80
    targetPort: 8080  # 指向 Pod 的 8080
  type: ClusterIP
