apiVersion: v1
kind: Service
metadata:
  name: demo-nginx-service
  labels:
    app: demo
spec:
  selector:
    app: demo
  ports:
  - protocol: TCP
    port: 80          # ClusterIP 仍然提供 80
    targetPort: 8080  # 對應到 Pod 內部的 8080
  type: ClusterIP
