apiVersion: v1
kind: Service
metadata:
  name: demo-nginx-service
  labels:
    app: demo
spec:
  selector:
    app: demo
  ports:
  - protocol: TCP
    port: 80         # ClusterIP 對外還是 80
    targetPort: 8080 # 對應 Pod 的 containerPort
  type: ClusterIP
